// This file has been autogenerated.
// Check out dpush-tests.js for re-generation instructions.

exports.scopes = [[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"]}")
  .reply(200, "{\"multicast_id\":7700222069911008280,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944021999919%4ce392b1f9fd7ecd\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"],\"data\":{\"message\":\"a message\"}}")
  .reply(200, "{\"multicast_id\":5280647157980830621,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944022073849%4ce392b1f9fd7ecd\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"],\"data\":{\"symbol\":\"msft\",\"price\":\"26.00\"}}")
  .reply(200, "{\"multicast_id\":9025790059549895993,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944022134398%4ce392b1f9fd7ecd\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\",\"invalid registration id\"],\"data\":{\"symbol\":\"msft\",\"price\":\"26.00\"}}")
  .reply(200, "{\"multicast_id\":7311331641720087405,\"success\":1,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944022200525%4ce392b1f9fd7ecd\"},{\"error\":\"InvalidRegistration\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"]}")
  .reply(401, "<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n", { 'content-type': 'text/html; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"]}")
  .reply(200, "{\"multicast_id\":6569625792005057535,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944022331392%4ce392b1f9fd7ecd\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"],\"data\":{\"message\":\"a message\"}}")
  .reply(200, "{\"multicast_id\":8584412412484917441,\"success\":1,\"failure\":0,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944022393742%4ce392b1f9fd7ecd\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\",\"invalid registration id\"],\"data\":{\"message\":\"a message\"}}")
  .reply(200, "{\"multicast_id\":6086110983945745938,\"success\":1,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"message_id\":\"0:1355944022458795%4ce392b1f9fd7ecd\"},{\"error\":\"InvalidRegistration\"}]}", { 'content-type': 'application/json; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"data\":{\"message\":\"a message\"}}")
  .reply(400, "Missing \"registration_ids\" field\n", { 'content-type': 'text/plain; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }],
[function (nock) { var result = 
nock('https://android.googleapis.com')
  .post('/gcm/send', "{\"registration_ids\":[\"APA91bG4R6JehqqPEbO93l699bnhFHDUd_E7V0_5KQ8sRPrhkqLfR7TgkiXI7YG6T0WBw3mqh0iwwnhbZNXJS4fIrmJCipp7hlA1CYK9AKTen3IeE5rvzBDTw_RdXXE_mRfsK-CNF3baPn4WPDf5E6UouUMrmWEBVVFEbxsHeRsOGLWgYvm9CCE\"],\"data\":{\"message\":\"a message\"}}")
  .reply(401, "<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n", { 'content-type': 'text/html; charset=UTF-8',
  date: 'Wed, 19 Dec 2012 19:07:02 GMT',
  expires: 'Wed, 19 Dec 2012 19:07:02 GMT',
  'cache-control': 'private, max-age=0',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  server: 'GSE',
  'transfer-encoding': 'chunked' });
 return result; }]];